language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

services:
  - riak

install:
    - riak-admin bucket-type create maps '{"props":{"datatype":"map"}}'
    - riak-admin bucket-type activate maps